export default [
  "Meditation is intermittent fasting for the mind.Too much sugar leads to a heavy body, and too many distractions lead to a heavy mind.Time spent undistracted and alone, in self-examination, journaling, meditation, resolves the unresolved and takes us from mentally fat to fit.",
  "Forty hour workweeks are a relic of the Industrial Age. Knowledge workers function like athletes — train and sprint, then rest and reassess.",
  "A fit body, a calm mind, a house full of love. These things cannot be bought — they must be earned.",
  "Information is everywhere but its meaning is created by the observer that interprets it. Meaning is relative and there is no objective, over-arching meaning.",
  "If you’re more passionate about founding a business than the business itself, you can fall into a ten year trap. Better to stay emotionally unattached and select the best opportunity that arises. Applies to relationships too.",
  "Sophisticated foods are bittersweet (wine, beer, coffee, chocolate). Addictive relationships are cooperative and competitive. Work becomes flow at the limits of ability. The flavor of life is on the edge.",
  "The fundamental delusion — there is something out there that will make me happy and fulfilled forever.",
  "Success is the enemy of learning. It can deprive you of the time and the incentive to start over. Beginner’s mind also needs beginner’s time.",
  "A contrarian isn’t one who always objects — that’s a confirmist of a different sort. A contrarian reasons independently, from the ground up, and resists pressure to conform.",
  "Before you can lie to another, you must first lie to yourself.",
  "Even today, what to study and how to study it are more important than where to study it and for how long. The best teachers are on the Internet. The best books are on the Internet. The best peers are on the Internet. The tools for learning are abundant. It’s the desire to learn that’s scarce.",
  "This is such a short and precious life that it’s really important that you don’t spend it being unhappy.",
  "You make your own luck if you stay at it long enough.",
  "The power to make and break habits and learning how to do that is really important.",
  "Happiness is a choice and a skill and you can dedicate yourself to learning that skill and making that choice.",
  "We’re not really here for that long and we don’t really matter that much. And nothing that we do lasts. So eventually you will fade. Your works will fade. Your children will fade. Your thoughts will fade. It will all be gone.",
  "A rational person can find peace by cultivating indifference to things outside of their control.",
  "The first rule of handling conflict is don’t hang around people who are constantly engaging in conflict.",
  "The problem happens when we have multiple desires. When we have fuzzy desires. When we want to do ten different things and we’re not clear about which is the one we care about.",
  "People spend too much time doing and not enough time thinking about what they should be doing.",
  "The people who succeed are irrationally passionate about something.",
  "I don’t plan. I’m not a planner. I prefer to live in the moment and be free and to flow and to be happy.",
  "If you try to micromanage yourself all you’re going to do is make yourself miserable.",
  "Desire is a contract that you make with yourself to be unhappy until you get what you want.",
  "Be present above all else.",
  "All the benefits in life come from compound interest — money, relationships, habits — anything of importance.",
  "If you can’t see yourself working with someone for life, don’t work with them for a day.",
  "Earn with your mind, not your time.",
  "Humans are basically habit machines… I think learning how to break habits is actually a very important meta skill and can serve you in life almost better than anything else.",
  "It’s the mark of a charlatan to try and explain simple things in complex ways and it’s the mark of a genius to explain complicated things in simple ways.",
  "You’re never going to get rich renting out your time.",
  "Clear thinkers appeal to their own authority.",
  "Think clearly from the ground up. Understand and explain from first principles. Ignore society and politics. Acknowledge what you have. Control your emotions.",
  "Cynicism is easy. Mimicry is easy. Optimistic contrarians are the rarest breed.",
  "If you’re desensitized to the fact that you’re going to die, consider it a different way. As far as you’re concerned, this world is going to end. Now what?",
  "Following your genuine intellectual curiosity is a better foundation for a career than following whatever is making money right now.",
  "One of the most damaging and widespread social beliefs is the idea that most adults are incapable of learning new skills.",
  "A personal metric: how much of the day is spent doing things out of obligation rather than out of interest?",
  "Caught in a funk? Use meditation, music, and exercise to reset your mood. Then choose a new path to commit emotional energy for rest of day.",
  "To be honest, speak without identity.",
  "A rational person can find peace by cultivating indifference to things outside of their control.",
  "People who live far below their means enjoy a freedom that people busy upgrading their lifestyles can’t fathom.",
  "We feel guilt when we no longer want to associate with old friends and colleagues who haven’t changed. The price, and marker, of growth.",
  "The most important trick to be happy is to realize that happiness is a choice that you make and a skill that you develop. You choose to be happy, and then you work at it. It’s just like building muscles.",
  "Don’t do things that you know are morally wrong. Not because someone is watching, but because you are. Self-esteem is just the reputation that you have with yourself.",
  "Anger is a hot coal that you hold in your hand while waiting to throw it at someone else.' (Buddhist saying)",
  "All the real benefits of life come from compound interest.",
  "Total honesty at all times. It’s almost always possible to be honest & positive.",
  "Truth is that which has predictive power.",
  "Watch every thought. Always ask, why am I having this thought?",
  "Love is given, not received.",
  "Don’t take yourself so seriously. You’re just a monkey with a plan.",
  "The three big ones in life are wealth, health, and happiness. We pursue them in that order, but their importance is reverse",
  "Maybe happiness is not something you inherit or even choose, but a highly personal skill that can be learned, like fitness or nutrition.",
  "Today, I believe happiness is really a default state. Happiness is there when you remove the sense of something missing in your life.",
  "Enlightenment is the space between your thoughts.",
  "Every moment has to be complete in and of itself.",
  "So I have no time for short-term things: dinners with people I won’t see again, tedious ceremonies to please tedious people, traveling to places that I wouldn’t go to on vacation.",
  "You can change it, you can accept it, or you can leave it. What is not a good option is to sit around wishing you would change it but not changing it, wishing you would leave it but not leaving it, and not accepting it. It’s that struggle, that aversion, that is responsible for most of our misery. The phrase that I use the most to myself in my head is one word: accept.",
  "I don’t have time is just saying it’s not a priority.",
  "Every positive thought even has a seed of a negative thought within it and vice versa, which is why a lot of greatness in life comes out of suffering.",
  "To me, happiness is not about positive thoughts. It’s not about negative thoughts. It’s about the absence of desire.",
  "Happiness to me is mainly not suffering, not desiring, not thinking too much about the future or the past, really embracing the present moment and the reality of what is, and the way it is.",
  "Nature has no concept of happiness or unhappiness. Nature follows unbroken mathematical laws and a chain of cause and effect from the Big Bang to now.",
  "The world just reflects your own feelings back at you. Reality is neutral. Reality has no judgments.",
  "There are no external forces affecting your emotions—as much as it may feel that way.",
  "Happiness is what’s there when you remove the sense that something is missing in your life.",
  "We think of ourselves as fixed and the world as malleable, but it’s really we who are malleable and the world is largely fixed.",
  "Real happiness only comes as a side-effect of peace.",
  "A rational person can find peace by cultivating indifference to things outside of their control.",
  "The real truths are heresies. They cannot be spoken. Only discovered, whispered, and perhaps read.",
  "There is no meaning to life. There is no purpose to life. Osho said, “It’s like writing on water or building houses of sand.",
  "Happiness is a state where nothing is missing.",
  "If you don’t love yourself who will?",
  "Escape competition through authenticity.",
  "School, politics, sports, and games train us to compete against others. True rewards — wealth, knowledge, love, fitness, and equanimity — come from ignoring others and improving ourselves.",
  "Signaling virtue is a vice.",
  "Reality is neutral. Our reactions reflect back and create our world. Judge, and feel separate and lonely. Anger, and lose peace of mind. Cling, and live in anxiety. Fantasize, and miss the present. Desire, and suffer until you have it. Heaven and hell are right here, right now.",
  "A busy mind accelerates the perceived passage of time. Buy more time by cultivating peace of mind.",
  "Doctors won’t make you healthy. Nutritionists won’t make you slim. Teachers won’t make you smart. Gurus won’t make you calm. Mentors won’t make you rich. Trainers won’t make you fit. Ultimately, you have to take responsibility. Save yourself.",
  "You can have the mind or you can have the moment.",
  "No one is going to value you more than you value yourself.",
  "A busy calendar and a busy mind will destroy your ability to create anything great.",
  "The greatest superpower is the ability to change yourself.",
  "People spend too much time doing and not enough time thinking about what they should be doing.",
  "Most of modern life, all our diseases, are diseases of abundance, not diseases of scarcity.",
  "That’s the fundamental delusion – that there is something out there that will make you happy forever.",
  "As long as you can keep taking shots on goal, and you keep getting back up, eventually you’ll get through. Just stick at it.",
  "True happiness comes out of peace. Peace comes out of many things, but it comes from fundamentally understanding yourself.",
  "Nothing you do is going to matter that much in the long run. Don’t take yourself so seriously.",
  "If you could literally just sit for 30 minutes and be happy, you are successful.",
  "The modern mind is overstimulated and the modern body is understimulated and overfed. Meditation, exercise, and fasting restore an ancient balance.",
  "A happy, calm, and peaceful person will make better decisions. So if you want to operate at peak performance, you have to learn how to tame your mind.",
  "Cynicism is easy. Mimicry is easy. Optimistic contrarians are the rarest breed.",
  "School, politics, sports, and games train us to compete against others. True rewards — wealth, knowledge, love, fitness, and equanimity — come from ignoring others and improving ourselves.",
  "When you’re healthy you have 10000 needs, but when you’re sick you only have one need.",
  "You can escape competition through authenticity, when you realize that no one can compete with you on being you.",
  "You have to put in the time, but more important is the judgment. The direction you’re heading in matters more than how fast you drive.",
  "The world doesn’t always give what you want, but it often gives you what you need.",
  "A fit body, a calm mind, a house full of love. These things cannot be bought — they must be earned.",
  "You want to be rich and anonymous, not poor and famous.",
  "The phrase that I use the most to myself in my head is I just tell myself one word: accept.",
  "Whether in commerce, science, or politics, history remembers the artists.",
  "Pick your one overwhelming desire. It’s okay to suffer over that one. But on all the other desires, let them go so you can be calm and peaceful and relaxed.",
  "I want to see truth. I want to see the world the way it is. Not through my filters. Not through my desires. Not through the way that other people want me to see it. And I want to accept it the way it is.",
  "Asymmetric opportunities: Invest in startups. Start a company. Create a book, podcast, video. Create a (software) product. Go on many first dates. Go to a cocktail party. Read a Lindy book. Move to a big city. Buy Bitcoin. Tweet.",
  "You’re meant to do something. You’re not just meant to lie there in the sand and meditate all day long. You should self-actualize. You should do what you are meant to do.",
  "A vacation is a very expensive way to schedule the time to read a book in peace.",
  "If you’re smart, you should be able to figure out how to be happy. Otherwise, you’re not that smart.",
  "More drugs are taken to quiet the mind than to heal the body.",
  "Suffering is a moment of clarity, when you can no longer deny the truth of a situation and are forced into uncomfortable change. Inside suffering is the seed of change.",
  "It’s kind of a disease – social media is making celebrities of all of us and celebrities are the most miserable people in the world.",
  "Over time, as you judge, judge, judge, you invariably judge people. You judge yourself. You separate yourself from everything, and then you end up lonely.",
  "When you’re on your death bed, when you’re on your last day, you’d give up every dollar in the bank for a few days, another hour, another minute.",
  "We don’t always get what we want, but sometimes what is happening is for the best. The sooner you can accept it as a reality, the sooner you can adapt to it.",
  "All that exists is this moment; it’s all there is. There is no future. That’s a fiction in your head that… nobody can predict the future.",
  "My biggest fear is that I’m going to die without having really lived. I think everybody has that fear at some core level.",
  "The best exercise is the one you enjoy doing every day.",
  "Your real resumé is a painful recounting of all of your struggles.",
  "When it comes to medicine and nutrition, subtract before you add.",
  "To measure the quality of your life, simply do nothing, and see how it feels.",
  "I think it just helps to be very aware that fundamentally, there are no adults. Everyone is making it up as they go along. You have to find your own path, picking, choosing, taking and discarding as you see fit.",
  "Don’t return it, give it away. Don’t keep fixing it, create something new. Don’t force the relationship, find someone else.",
  "Knowledge is discovered by all of us, each adding to the whole. Wisdom is rediscovered by each of us, one at a time.",
  "If you want to be successful, surround yourself with people who are more successful than you are. If you want to be happy, surround yourself with people who are less successful.",
  "You always have three options. You can change it, you can accept it, or you can leave it.",
  "Just focus on the one or two really really important things, and everything else, just surrender to it. Just take it as it comes. Just accept it. Be glad with it. Be happy that you’re in this world.",
  "When I look back on my life, I want to say I saw the world the way it was.",
  "My number one priority in life, above my happiness, above my family, above my work, is my own health. It starts with my physical health. Second, it’s my mental health. Third, it’s my spiritual health.",
  "On what is the purpose of life: To keep growing and learning in the short period of time that you have. To seek truth and to accept things the way they are. To see the world the way it really is. Then, just to live your life. I think that’s it.",
  "If you look back at your life on your deathbed at all the interesting things you’ve done, they’re all going to be centered around the sacrifices you’ve made and the hard things that you did.",
  "When looking for a purpose to life, notice that most things are stepping stones, done for ulterior motives. True art, love, and play stand apart, as they are done for their own sakes.",
  "On the meaning of life: You get to make up your own answer and that’s the beauty of it. If there was a single answer, we wouldn’t be free.",
  "A personal metric: how much of the day is spent doing things out of obligation rather than out of interest?",
  "If you’re going to pick 3 cards in the hand you’re dealt, take intelligence, drive, and most importantly, emotional self-discipline.",
  "Stop caring about the impact and just be the best version of you possible – then you’ll naturally have an impact.",
  "There’s no certainty in life. You can put in the hours, you can put in the time, but you can’t really expect the outcome.",
  "On his morning routines: 1 hour meditation + 1 hour workout/yoga.",
  "Your closest friends are the ones you can have a relationship with about nothing.",
  "Everything you’re a winner at now in your life, you were a once a loser at.",
  "I wish I had done all of the same things but with less emotion and less anger.",
  "I, and I alone, am responsible for everything I think and feel.",
  "Desire is a contract that you make with yourself to be unhappy until you get what you want.",
  "As you get older, you just realize that there’s no happiness in material possessions.",
  "Yoga cultivates Peace of Body. Meditation cultivates Peace of Mind.",
  "Internal happiness is reward from being in flow. Create, meditate, love, play. Clears the mind and leaves us in peace.",
  "We are born with happiness, we are intrinsically happy creatures but we become unhappy because our egos create desire.",
  "You can very slowly but steadily and methodically improve your happiness baseline, just like you can improve your fitness.",
  "If you’re a peaceful person, anything you do will be a happy activity.",
  "To me, peace is happiness at rest and happiness is peace in motion. You can convert peace to happiness anytime you want.",
  "In every moment, in everything that happens, you can look on the bright side of something. There are two ways of seeing almost everything.",
  "The problem happens when we have multiple desires. When we have fuzzy desires. When we want to do ten different things and we’re not clear about which is the one we care about.",
  "Enlightenment is the space between your thoughts. It isn’t this thing you achieve after 30 years of sitting in a corner meditating. It’s something you can achieve moment to moment and you can be a certain percentage enlightened every single day.",
  "People who live far below their means enjoy a freedom that people busy upgrading their lifestyles can’t fathom.",
  "Quick relaxation hack: “Drop face, soft belly”. The face is usually wearing a mask to signal to others. The belly is often chronically tensed in a fight-or-flight response.",
  "Children are happy because: 1) They’re not self conscious 2) They lack a sense of time pressure 3) They’ve no goals. The bottom line is they are living from moment to moment, and the mind is not there to interfere in their bliss.",
  "I’m not a busy person and I’m not busy because I refuse to schedule things.",
  "Looking forward to holidays takes the joy out of everyday.",
  "By the time people realize that they have enough money, they’ve lost their time and their health.",
  "The ultimate purpose of money is so that you do not have to be in a specific place at a specific time doing anything you don’t want to do.",
  "The first thing you realize when you make a bunch of money is that you’re still the same person.",
  "Read what you love until you love to read.",
  "Just be you and wait for the people who want that.",
  "If you don’t love yourself, who will?",
  "The clear thinking comes from having time to reflect and to pursue your genuine intellectual curiosity.",
  "The advantage of meditation is not that you’re suddenly going to gain the superpower to control your internal state, it’s that you will recognize just how out of control your mind is.",
  "What I find is that 90 percent of thoughts that I have are fear. 90 percent are fear based. The other 10 percent are probably desire based.",
  "A busy mind can often rob you of peace of mind. The peace that we seek is not peace of mind, it’s peace from mind.",
  "Success is the enemy of learning. It can deprive you of the time and the incentive to start over. Beginner’s mind also needs beginner’s time.",
  "I think it’s really worth – whenever you can in life, if you have the choice – optimizing for independence rather than optimizing for pay.",
  "You have to surrender, at least a little bit, to be the best version of yourself possible.",
];
